export const links = [
  {
    name: "Work Areas",
    submenu: true,
    sublink: [
      { name: "Open Office", link: "/showcase" },
      { name: "Private Office", link: "/" },
      { name: "Work Lounge", link: "/" },
    ],
  },
  {
    name: "Meeting Spaces",
    submenu: true,
    sublink: [
      { name: "Assembly", link: "/" },
      { name: "Boardroom", link: "/" },
      { name: "Brainstorm Room", link: "/" },
      { name: "Breakout Space", link: "/" },
      { name: "Large Meeting Room", link: "/" },
      { name: "Large Open Meeting Space", link: "/" },
      { name: "Meeting Point", link: "/" },
      { name: "Small Meeting Room", link: "/" },
      { name: "Small Open Meeting Space", link: "/" },
      { name: "Training Room", link: "/" },
    ],
  },
  {
    name: "Support Spaces",
    submenu: true,
    sublink: [
      { name: "Bar", link: "/" },
      { name: "Bike Storage", link: "/" },
      { name: "Cafeteria", link: "/" },
      { name: "Child Care", link: "/" },
      { name: "Elevator Lobby", link: "/" },
      { name: "Games Room", link: "/" },
      { name: "Gym / Fitness Center", link: "/" },
      { name: "Kitchen", link: "/" },
      { name: "Library", link: "/" },
      { name: "Locker Area", link: "/" },
      { name: "Massage Room", link: "/" },
      { name: "Micro Pantry", link: "/" },
      { name: "Mother's Room", link: "/" },
      { name: "Pantry Area / Coffee Point", link: "/" },
      { name: "Phone / Study Booth", link: "/" },
      { name: "Podcast / Recording Studio", link: "/" },
      { name: "Reception / Waiting Area", link: "/" },
      { name: "Relaxation / Nap Room", link: "/" },
      { name: "Restroom", link: "/" },
    ],
  },

  {
    name: "Features",
    submenu: true,
    sublink: [
      { name: "Acoustic Ceiling Baffle", link: "/" },
      { name: "Acoustic Ceiling Panel", link: "/" },
      { name: "Acoustic Wall Panel", link: "/" },
      { name: "Barn Door", link: "/" },
      { name: "Booking Screen", link: "/" },
      { name: "Ceiling Fans", link: "/" },
      { name: "Ceiling-Mounted Display", link: "/" },
      { name: "Chalkboard", link: "/" },
      { name: "Column", link: "/" },
      { name: "Curtain", link: "/" },
      { name: "Details / Close-up Photos", link: "/" },
      { name: "Exposed Duct", link: "/" },
      { name: "Exterior", link: "/" },
      { name: "Folding / Moveable Walls", link: "/" },
      { name: "Glass Walls", link: "/" },
      { name: "Green Wall", link: "/" },
      { name: "Guardrail", link: "/" },
      { name: "Hallway", link: "/" },
      { name: "Lectern", link: "/" },
      { name: "Partition", link: "/" },
      { name: "People", link: "/" },
      { name: "Pin Board", link: "/" },
      { name: "Plans / Drawings", link: "/" },
      { name: "Plants", link: "/" },
      { name: "Projection Screen", link: "/" },
      { name: "Shipping Containers", link: "/" },
      { name: "Slides", link: "/" },
      { name: "Spiral Stairs", link: "/" },
      { name: "Stairs", link: "/" },
      { name: "Terrace", link: "/" },
      { name: "Video Conferencing", link: "/" },
      { name: "Video Wall", link: "/" },
      { name: "View", link: "/" },
      { name: "Wall-Mounted Display", link: "/" },
      { name: "Whiteboard", link: "/" },
      { name: "Whiteboard Wall", link: "/" },
      { name: "World Map", link: "/" },
    ],
  },

  {
    name: "Flooring",
    submenu: true,
    sublink: [
      { name: "Area Rug", link: "/" },
      { name: "Carpet", link: "/" },
      { name: "Cement Floor", link: "/" },
      { name: "Parquet Floor", link: "/" },
      { name: "Wood Floor", link: "/" },
    ],
  },

  {
    name: "Lighting",
    submenu: true,
    sublink: [
      { name: "Backlight / Panel", link: "/" },
      { name: "Bare Bulb", link: "/" },
      { name: "Chandelier", link: "/" },
      { name: "Cove Lighting", link: "/" },
      { name: "Cylinder / Round", link: "/" },
      { name: "Floor Lamp", link: "/" },
      { name: "In-floor", link: "/" },
      { name: "Lay-In / Troffer", link: "/" },
      { name: "Linear", link: "/" },
      { name: "Neon", link: "/" },
      { name: "Pendant", link: "/" },
      { name: "Perimeter / Grazer", link: "/" },
      { name: "Recessed Downlight", link: "/" },
      { name: "Recessed Lighting", link: "/" },
      { name: "Sconce", link: "/" },
      { name: "Stair and Handrail", link: "/" },
      { name: "Table Lamp", link: "/" },
      { name: "Task Light", link: "/" },
      { name: "Track / Directional", link: "/" },
    ],
  },

  {
    name: "Materials",
    submenu: true,
    sublink: [
      { name: "Brick", link: "/" },
      { name: "Fake Grass", link: "/" },
      { name: "OSB", link: "/" },
      { name: "Plywood", link: "/" },
      { name: "Wood", link: "/" },
    ],
  },

  {
    name: "Environmental Graphics",
    submenu: true,
    sublink: [
      { name: "Branding", link: "/" },
      { name: "Glass Graphics", link: "/" },
      { name: "Signs & Wayfinding", link: "/" },
      { name: "Street Art", link: "/" },
      { name: "Wall Graphics", link: "/" },
    ],
  },

  {
    name: "Seating & Tables",
    submenu: true,
    sublink: [
      { name: "Banquette Seating", link: "/" },
      { name: "Bar Stool", link: "/" },
      { name: "Bench", link: "/" },
      { name: "Booth Seating", link: "/" },
      { name: "Chair", link: "/" },
      { name: "Coffee Table", link: "/" },
      { name: "Game / Billiards Table", link: "/" },
      { name: "Highback Sofa / Chair", link: "/" },
      { name: "Lounge Chair", link: "/" },
      { name: "Low Stool", link: "/" },
      { name: "Occasional Table", link: "/" },
      { name: "Ottoman / Pouf", link: "/" },
      { name: "Perch / Ledge", link: "/" },
      { name: "Personal / Laptop Table", link: "/" },
      { name: "Picnic Table", link: "/" },
      { name: "Task Chair", link: "/" },
      { name: "Task Stool", link: "/" },
      { name: "Tiered-Seating", link: "/" },
      { name: "Training Table", link: "/" },
    ],
  },
];
